class Trip {
  final String id;
  final String userId;
  final String name;
  final String? description;
  final String status; // 'planning', 'active', 'completed', 'archived'
  final bool isActive;
  final DateTime? startDate;
  final DateTime? endDate;
  final double totalDistance;
  final int totalDurationMinutes;
  final DateTime createdAt;
  final DateTime updatedAt;

  Trip({
    required this.id,
    required this.userId,
    required this.name,
    this.description,
    this.status = 'planning',
    this.isActive = false,
    this.startDate,
    this.endDate,
    this.totalDistance = 0,
    this.totalDurationMinutes = 0,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Trip.fromJson(Map<String, dynamic> json) {
    return Trip(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      name: json['name'] as String,
      description: json['description'] as String?,
      status: json['status'] as String? ?? 'planning',
      isActive: json['is_active'] as bool? ?? false,
      startDate: json['start_date'] != null
          ? DateTime.parse(json['start_date'] as String)
          : null,
      endDate: json['end_date'] != null
          ? DateTime.parse(json['end_date'] as String)
          : null,
      totalDistance: (json['total_distance'] as num?)?.toDouble() ?? 0,
      totalDurationMinutes: json['total_duration_minutes'] as int? ?? 0,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'name': name,
      'description': description,
      'status': status,
      'is_active': isActive,
      'start_date': startDate?.toIso8601String(),
      'end_date': endDate?.toIso8601String(),
      'total_distance': totalDistance,
      'total_duration_minutes': totalDurationMinutes,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  /// Factory constructor for creating a new trip
  factory Trip.create({
    required String userId,
    required String name,
    String? description,
    DateTime? startDate,
    DateTime? endDate,
  }) {
    final now = DateTime.now();
    return Trip(
      id: '', // Will be generated by server
      userId: userId,
      name: name,
      description: description,
      status: 'planning',
      isActive: false,
      startDate: startDate,
      endDate: endDate,
      totalDistance: 0,
      totalDurationMinutes: 0,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Create a copy with modified fields
  Trip copyWith({
    String? id,
    String? userId,
    String? name,
    String? description,
    String? status,
    bool? isActive,
    DateTime? startDate,
    DateTime? endDate,
    double? totalDistance,
    int? totalDurationMinutes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Trip(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      name: name ?? this.name,
      description: description ?? this.description,
      status: status ?? this.status,
      isActive: isActive ?? this.isActive,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      totalDistance: totalDistance ?? this.totalDistance,
      totalDurationMinutes: totalDurationMinutes ?? this.totalDurationMinutes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
