import 'package:json_annotation/json_annotation.dart';

part 'trip.g.dart';

@JsonSerializable()
class Trip {
  final String id;
  final String userId;
  final String name;
  final String? description;
  final String status; // 'planning', 'active', 'completed', 'archived'
  final bool isActive;
  final DateTime? startDate;
  final DateTime? endDate;
  final double totalDistance;
  final int totalDurationMinutes;
  final DateTime createdAt;
  final DateTime updatedAt;

  Trip({
    required this.id,
    required this.userId,
    required this.name,
    this.description,
    this.status = 'planning',
    this.isActive = false,
    this.startDate,
    this.endDate,
    this.totalDistance = 0,
    this.totalDurationMinutes = 0,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Trip.fromJson(Map<String, dynamic> json) => _$TripFromJson(json);

  Map<String, dynamic> toJson() => _$TripToJson(this);

  /// Factory constructor for creating a new trip
  factory Trip.create({
    required String userId,
    required String name,
    String? description,
    DateTime? startDate,
    DateTime? endDate,
  }) {
    final now = DateTime.now();
    return Trip(
      id: '', // Will be generated by server
      userId: userId,
      name: name,
      description: description,
      status: 'planning',
      isActive: false,
      startDate: startDate,
      endDate: endDate,
      totalDistance: 0,
      totalDurationMinutes: 0,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Create a copy with modified fields
  Trip copyWith({
    String? id,
    String? userId,
    String? name,
    String? description,
    String? status,
    bool? isActive,
    DateTime? startDate,
    DateTime? endDate,
    double? totalDistance,
    int? totalDurationMinutes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Trip(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      name: name ?? this.name,
      description: description ?? this.description,
      status: status ?? this.status,
      isActive: isActive ?? this.isActive,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      totalDistance: totalDistance ?? this.totalDistance,
      totalDurationMinutes: totalDurationMinutes ?? this.totalDurationMinutes,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
