import 'package:json_annotation/json_annotation.dart';

part 'user_profile.g.dart';

@JsonSerializable()
class UserProfile {
  final String id;
  final String userId;
  final String? firstName;
  final String? lastName;
  final String email;
  final String? phoneNumber;
  final String? profilePictureUrl;
  final String? bio;
  final String? dateOfBirth;
  final String? gender;
  final String? address;
  final String? city;
  final String? country;
  final Map<String, dynamic>? preferences;
  final DateTime createdAt;
  final DateTime updatedAt;

  UserProfile({
    required this.id,
    required this.userId,
    this.firstName,
    this.lastName,
    required this.email,
    this.phoneNumber,
    this.profilePictureUrl,
    this.bio,
    this.dateOfBirth,
    this.gender,
    this.address,
    this.city,
    this.country,
    this.preferences,
    required this.createdAt,
    required this.updatedAt,
  });

  factory UserProfile.fromJson(Map<String, dynamic> json) =>
      _$UserProfileFromJson(json);

  Map<String, dynamic> toJson() => _$UserProfileToJson(this);

  /// Factory constructor for creating a new user profile during signup
  factory UserProfile.create({
    required String userId,
    required String email,
    String? firstName,
    String? lastName,
    String? phoneNumber,
    String? profilePictureUrl,
    String? bio,
    String? dateOfBirth,
    String? gender,
    String? address,
    String? city,
    String? country,
    Map<String, dynamic>? preferences,
  }) {
    final now = DateTime.now();
    return UserProfile(
      id: '', // Will be generated by server
      userId: userId,
      firstName: firstName,
      lastName: lastName,
      email: email,
      phoneNumber: phoneNumber,
      profilePictureUrl: profilePictureUrl,
      bio: bio,
      dateOfBirth: dateOfBirth,
      gender: gender,
      address: address,
      city: city,
      country: country,
      preferences: preferences ?? {},
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Create a copy of this profile with modified fields
  UserProfile copyWith({
    String? id,
    String? userId,
    String? firstName,
    String? lastName,
    String? email,
    String? phoneNumber,
    String? profilePictureUrl,
    String? bio,
    String? dateOfBirth,
    String? gender,
    String? address,
    String? city,
    String? country,
    Map<String, dynamic>? preferences,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return UserProfile(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      email: email ?? this.email,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      profilePictureUrl: profilePictureUrl ?? this.profilePictureUrl,
      bio: bio ?? this.bio,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      gender: gender ?? this.gender,
      address: address ?? this.address,
      city: city ?? this.city,
      country: country ?? this.country,
      preferences: preferences ?? this.preferences,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
